import { defineCollection, z } from 'astro:content';

// Internal collection name is kept as "warehouses" to preserve the existing Astro structure and Decap CMS automation.
const warehouses = defineCollection({
  type: 'content',
  schema: z.object({
    published: z.boolean().default(true),
    order: z.number().default(1),
    pageSlug: z.string(),
    block: z.string().default('Складской объект'),
    floor: z.string().default('1'),
    area: z.number(),
    areaMin: z.number().optional(),
    areaMax: z.number().optional(),
    workplaces: z.string().default('по запросу'),
    ready: z.enum(['Действующий', 'Строящийся']).default('Действующий'),
    warehouseLayout: z.string().default('сухой склад'),
    title: z.string(),
    detailTitle: z.string(),
    seoTitle: z.string(),
    description: z.string(),
    imageAlt: z.string().default('Складской объект в Ташкенте'),
    intro: z.string(),
    features: z.array(z.string()).default([]),
    detailFeatures: z.array(z.string()).default([]),
    planImage: z.string(),
    mainImage: z.string(),
    gallery: z.array(z.string()).default([]),
    presentationFile: z.string().default('/files/placeholder-presentation-1.pdf'),
    region: z.string().default('Ташкент'),
    city: z.string().default('Ташкент'),
    district: z.string().default('Ташкент'),
    address: z.string().default('Ташкент, Узбекистан'),
    propertyType: z.string().default('Склад'),
    warehouseClass: z.string().default('B'),
    ceilingHeight: z.string().default('по запросу'),
    dockDoors: z.string().default('по запросу'),
    temperature: z.string().default('+15 - +25 C'),
    temperatureMode: z.enum(['+15 - +25 C', 'Холодильник', 'Естественное']).default('Естественное'),
    leaseType: z.enum(['Сухая аренда', 'Стеллажная аренда', '3PL']).default('Сухая аренда'),
    builtYear: z.number().optional(),
    price: z.string().default('По запросу'),
    availableNow: z.boolean().default(true),
    mapX: z.number().default(50),
    mapY: z.number().default(50),
    latitude: z.number().default(41.311081),
    longitude: z.number().default(69.240562),
  }),
});

export const collections = { warehouses };
