const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const allowed=new Set(["published","title","detailTitle","seoTitle","description","intro","area","areaMin","areaMax","price","ready","region","city","district","address","propertyType","warehouseClass","ceilingHeight","temperature","temperatureMode","leaseType","dockDoors","floor","builtYear","availableNow","latitude","longitude","mainImage","planImage","gallery","imageAlt"]);
const decodeBase64=(value)=>{const cleaned=String(value||"").split(String.fromCharCode(10)).join("").split(String.fromCharCode(13)).join("");const binary=atob(cleaned);return new TextDecoder().decode(Uint8Array.from(binary,(char)=>char.charCodeAt(0)));};
const encodeBase64=(value)=>{const bytes=new TextEncoder().encode(value);let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary);};
const yamlValue=(value)=>{if(Array.isArray(value))return JSON.stringify(value.map((item)=>String(item)));if(typeof value==="number"){if(!Number.isFinite(value))throw Error("Invalid number");return String(value);}if(typeof value==="boolean")return value?"true":"false";return JSON.stringify(String(value));};
const createFrontmatter=(slug,fields)=>{const title=String(fields.title||fields.detailTitle||"Новый складской объект"),detailTitle=String(fields.detailTitle||title),description=String(fields.description||fields.intro||("Складской объект: "+title)),intro=String(fields.intro||description),area=Number(fields.area||0),latitude=Number(fields.latitude||41.311081),longitude=Number(fields.longitude||69.240562);const values={published:true,order:9999,pageSlug:slug,block:title,floor:String(fields.floor||"1"),area:Number.isFinite(area)?area:0,workplaces:"по запросу",ready:String(fields.ready||"Действующий"),warehouseLayout:String(fields.leaseType||"Сухая аренда"),title,detailTitle,seoTitle:String(fields.seoTitle||title),description,imageAlt:String(fields.imageAlt||("Складской объект: "+title)),intro,planImage:String(fields.planImage||"/images/objects/object-1-plan.svg"),mainImage:String(fields.mainImage||"/images/objects/object-1-main.svg"),presentationFile:"/files/placeholder-presentation-1.pdf",region:String(fields.region||"Ташкент"),city:String(fields.city||"Ташкент"),district:String(fields.district||"Ташкент"),address:String(fields.address||"Ташкент, Узбекистан"),propertyType:String(fields.propertyType||"Склад"),warehouseClass:String(fields.warehouseClass||"B"),ceilingHeight:String(fields.ceilingHeight||"по запросу"),dockDoors:String(fields.dockDoors||"по запросу"),temperature:String(fields.temperature||"+15 - +25 C"),temperatureMode:String(fields.temperatureMode||"Естественное"),leaseType:String(fields.leaseType||"Сухая аренда"),price:String(fields.price||"По запросу"),availableNow:true,mapX:50,mapY:50,latitude:Number.isFinite(latitude)?latitude:41.311081,longitude:Number.isFinite(longitude)?longitude:69.240562};if(fields.builtYear!==undefined)values.builtYear=fields.builtYear;const lines=["---"];for(const [key,value] of Object.entries(values))lines.push(key+": "+yamlValue(value));lines.push("features: []","detailFeatures: []","gallery: "+yamlValue(Array.isArray(fields.gallery)?fields.gallery:[]),"---","");return lines.join(String.fromCharCode(10));};
const updateFrontmatter=(source,fields)=>{const crlf=String.fromCharCode(13,10),lf=String.fromCharCode(10),newline=source.includes(crlf)?crlf:lf;const lines=source.split(crlf).join(lf).split(lf);if(lines[0]!=="---")throw Error("Frontmatter start not found");let end=lines.indexOf("---",1);if(end<0)throw Error("Frontmatter end not found");for(const [key,value] of Object.entries(fields)){if(!allowed.has(key)||value===undefined)continue;const prefix=key+":",next=prefix+" "+yamlValue(value);let index=-1;for(let i=1;i<end;i++){if(lines[i]===prefix||lines[i].startsWith(prefix+" ")){index=i;break;}}if(index>=0){let removeCount=1;if(Array.isArray(value))while(index+removeCount<end&&lines[index+removeCount].startsWith("- "))removeCount++;lines.splice(index,removeCount,next);end=end-removeCount+1;}else{lines.splice(end,0,next);end++;}}return lines.join(newline);};
export async function onRequestPost({request,env}){
if(!env.GITHUB_TOKEN)return json({error:"GITHUB_TOKEN is not configured"},500);
let payload;try{payload=await request.json();}catch{return json({error:"Invalid JSON"},400);}
const create=payload&&payload.create===true;const slug=String(payload&&payload.slug||"").trim();if(!/^[a-z0-9-]+$/.test(slug))return json({error:"Invalid slug"},400);
const input=payload&&payload.fields&&typeof payload.fields==="object"&&!Array.isArray(payload.fields)?payload.fields:{},fields={};for(const [key,value] of Object.entries(input))if(allowed.has(key)&&value!==undefined)fields[key]=value;if(typeof fields.gallery==="string"){try{const parsed=JSON.parse(fields.gallery);fields.gallery=Array.isArray(parsed)?parsed.map((item)=>String(item)):[];}catch{fields.gallery=[];}}if(!Object.keys(fields).length)return json({error:"No supported fields"},400);
const repo=env.GITHUB_REPO||"SF55SF/arendasklada",branch=env.GITHUB_BRANCH||"main",path="src/content/warehouses/"+slug+".md";
const headers={Accept:"application/vnd.github+json",Authorization:"Bearer "+env.GITHUB_TOKEN,"User-Agent":"arendasklada-admin","X-GitHub-Api-Version":"2022-11-28"};
const readUrl="https://api.github.com/repos/"+repo+"/contents/"+path+"?ref="+encodeURIComponent(branch),currentResponse=await fetch(readUrl,{headers});
if(create&&currentResponse.ok)return json({error:"Объект с таким адресом уже существует"},409);
if(!currentResponse.ok){if(!(create&&currentResponse.status===404))return json({error:"GitHub read failed",status:currentResponse.status,details:await currentResponse.text()},currentResponse.status);const source=createFrontmatter(slug,fields),createResponse=await fetch("https://api.github.com/repos/"+repo+"/contents/"+path,{method:"PUT",headers:{...headers,"content-type":"application/json"},body:JSON.stringify({message:"Create warehouse "+slug+" from admin",content:encodeBase64(source),branch})});if(!createResponse.ok)return json({error:"GitHub create failed",status:createResponse.status,details:await createResponse.text()},createResponse.status);const created=await createResponse.json();return json({ok:true,created:true,path,commit:created.commit&&created.commit.sha||null});}
const current=await currentResponse.json(),source=decodeBase64(current.content);let updated;try{updated=updateFrontmatter(source,fields);}catch(error){return json({error:error instanceof Error?error.message:"Frontmatter update failed"},400);}if(updated===source)return json({ok:true,unchanged:true,path,sha:current.sha});
const saveResponse=await fetch("https://api.github.com/repos/"+repo+"/contents/"+path,{method:"PUT",headers:{...headers,"content-type":"application/json"},body:JSON.stringify({message:"Update warehouse "+slug+" from admin",content:encodeBase64(updated),sha:current.sha,branch})});if(!saveResponse.ok)return json({error:"GitHub save failed",status:saveResponse.status,details:await saveResponse.text()},saveResponse.status);const result=await saveResponse.json();return json({ok:true,path,commit:result.commit&&result.commit.sha||null});
}